package com.dianping.phoenix.lb.deploy.dao;

import com.dianping.phoenix.lb.deploy.model.AgentIdSequence;
import com.dianping.phoenix.lb.deploy.model.AgentIdSequenceExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface AgentIdSequenceMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	int countByExample(AgentIdSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	int deleteByExample(AgentIdSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long agentId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	int insert(AgentIdSequence record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	int insertSelective(AgentIdSequence record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	List<AgentIdSequence> selectByExampleWithRowbounds(AgentIdSequenceExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	List<AgentIdSequence> selectByExample(AgentIdSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	AgentIdSequence selectByPrimaryKey(Long agentId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(
			@Param("record")
			AgentIdSequence record,
			@Param("example")
			AgentIdSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	int updateByExample(
			@Param("record")
			AgentIdSequence record,
			@Param("example")
			AgentIdSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AgentIdSequence record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AgentIdSequence record);
}