package com.dianping.phoenix.lb.deploy.dao;

import com.dianping.phoenix.lb.deploy.model.DeployAgent;
import com.dianping.phoenix.lb.deploy.model.DeployAgentExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface DeployAgentMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	int countByExample(DeployAgentExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	int deleteByExample(DeployAgentExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	int insert(DeployAgent record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	int insertSelective(DeployAgent record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	List<DeployAgent> selectByExampleWithBLOBsWithRowbounds(DeployAgentExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	List<DeployAgent> selectByExampleWithBLOBs(DeployAgentExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	List<DeployAgent> selectByExampleWithRowbounds(DeployAgentExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	List<DeployAgent> selectByExample(DeployAgentExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	DeployAgent selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(
			@Param("record")
			DeployAgent record,
			@Param("example")
			DeployAgentExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(
			@Param("record")
			DeployAgent record,
			@Param("example")
			DeployAgentExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	int updateByExample(
			@Param("record")
			DeployAgent record,
			@Param("example")
			DeployAgentExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DeployAgent record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(DeployAgent record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DeployAgent record);
}