package com.dianping.phoenix.lb.deploy.dao.api;

import com.dianping.phoenix.lb.deploy.model.api.DeployTaskApi;
import com.dianping.phoenix.lb.deploy.model.api.DeployTaskApiExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface DeployTaskApiMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	int countByExample(DeployTaskApiExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	int deleteByExample(DeployTaskApiExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	int insert(DeployTaskApi record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	int insertSelective(DeployTaskApi record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	List<DeployTaskApi> selectByExampleWithBLOBsWithRowbounds(DeployTaskApiExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	List<DeployTaskApi> selectByExampleWithBLOBs(DeployTaskApiExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	List<DeployTaskApi> selectByExampleWithRowbounds(DeployTaskApiExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	List<DeployTaskApi> selectByExample(DeployTaskApiExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	DeployTaskApi selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(
			@Param("record")
			DeployTaskApi record,
			@Param("example")
			DeployTaskApiExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(
			@Param("record")
			DeployTaskApi record,
			@Param("example")
			DeployTaskApiExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	int updateByExample(
			@Param("record")
			DeployTaskApi record,
			@Param("example")
			DeployTaskApiExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DeployTaskApi record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(DeployTaskApi record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DeployTaskApi record);
}