package com.dianping.phoenix.lb.deploy.dao.api;

import com.dianping.phoenix.lb.deploy.model.api.DeployAgentApi;
import com.dianping.phoenix.lb.deploy.model.api.DeployAgentApiExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface DeployAgentApiMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	int countByExample(DeployAgentApiExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	int deleteByExample(DeployAgentApiExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	int insert(DeployAgentApi record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	int insertSelective(DeployAgentApi record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	List<DeployAgentApi> selectByExampleWithBLOBsWithRowbounds(DeployAgentApiExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	List<DeployAgentApi> selectByExampleWithBLOBs(DeployAgentApiExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	List<DeployAgentApi> selectByExampleWithRowbounds(DeployAgentApiExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	List<DeployAgentApi> selectByExample(DeployAgentApiExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	DeployAgentApi selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(
			@Param("record")
			DeployAgentApi record,
			@Param("example")
			DeployAgentApiExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(
			@Param("record")
			DeployAgentApi record,
			@Param("example")
			DeployAgentApiExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	int updateByExample(
			@Param("record")
			DeployAgentApi record,
			@Param("example")
			DeployAgentApiExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DeployAgentApi record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(DeployAgentApi record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DeployAgentApi record);
}