package com.dianping.phoenix.lb.deploy.model;

import java.io.Serializable;
import java.util.Date;

public class DeployVs implements Serializable {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_vs.id
	 *
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_vs.vs_name
	 *
	 * @mbggenerated
	 */
	private String vsName;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_vs.vs_tag
	 *
	 * @mbggenerated
	 */
	private String vsTag;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_vs.status
	 *
	 * @mbggenerated
	 */
	private DeployVsStatus status;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_vs.deploy_task_id
	 *
	 * @mbggenerated
	 */
	private Long deployTaskId;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_vs.begin_date
	 *
	 * @mbggenerated
	 */
	private Date beginDate;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_vs.end_date
	 *
	 * @mbggenerated
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_vs.creation_date
	 *
	 * @mbggenerated
	 */
	private Date creationDate;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_vs.last_modified_date
	 *
	 * @mbggenerated
	 */
	private Date lastModifiedDate;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_vs.old_vs_tag
	 *
	 * @mbggenerated
	 */
	private String oldVsTag;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_vs.summary_log
	 *
	 * @mbggenerated
	 */
	private String summaryLog;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_vs.id
	 *
	 * @return the value of deploy_vs.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_vs.id
	 *
	 * @param id the value for deploy_vs.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_vs.vs_name
	 *
	 * @return the value of deploy_vs.vs_name
	 * @mbggenerated
	 */
	public String getVsName() {
		return vsName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_vs.vs_name
	 *
	 * @param vsName the value for deploy_vs.vs_name
	 * @mbggenerated
	 */
	public void setVsName(String vsName) {
		this.vsName = vsName == null ? null : vsName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_vs.vs_tag
	 *
	 * @return the value of deploy_vs.vs_tag
	 * @mbggenerated
	 */
	public String getVsTag() {
		return vsTag;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_vs.vs_tag
	 *
	 * @param vsTag the value for deploy_vs.vs_tag
	 * @mbggenerated
	 */
	public void setVsTag(String vsTag) {
		this.vsTag = vsTag == null ? null : vsTag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_vs.status
	 *
	 * @return the value of deploy_vs.status
	 * @mbggenerated
	 */
	public DeployVsStatus getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_vs.status
	 *
	 * @param status the value for deploy_vs.status
	 * @mbggenerated
	 */
	public void setStatus(DeployVsStatus status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_vs.deploy_task_id
	 *
	 * @return the value of deploy_vs.deploy_task_id
	 * @mbggenerated
	 */
	public Long getDeployTaskId() {
		return deployTaskId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_vs.deploy_task_id
	 *
	 * @param deployTaskId the value for deploy_vs.deploy_task_id
	 * @mbggenerated
	 */
	public void setDeployTaskId(Long deployTaskId) {
		this.deployTaskId = deployTaskId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_vs.begin_date
	 *
	 * @return the value of deploy_vs.begin_date
	 * @mbggenerated
	 */
	public Date getBeginDate() {
		return beginDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_vs.begin_date
	 *
	 * @param beginDate the value for deploy_vs.begin_date
	 * @mbggenerated
	 */
	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_vs.end_date
	 *
	 * @return the value of deploy_vs.end_date
	 * @mbggenerated
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_vs.end_date
	 *
	 * @param endDate the value for deploy_vs.end_date
	 * @mbggenerated
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_vs.creation_date
	 *
	 * @return the value of deploy_vs.creation_date
	 * @mbggenerated
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_vs.creation_date
	 *
	 * @param creationDate the value for deploy_vs.creation_date
	 * @mbggenerated
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_vs.last_modified_date
	 *
	 * @return the value of deploy_vs.last_modified_date
	 * @mbggenerated
	 */
	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_vs.last_modified_date
	 *
	 * @param lastModifiedDate the value for deploy_vs.last_modified_date
	 * @mbggenerated
	 */
	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_vs.old_vs_tag
	 *
	 * @return the value of deploy_vs.old_vs_tag
	 * @mbggenerated
	 */
	public String getOldVsTag() {
		return oldVsTag;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_vs.old_vs_tag
	 *
	 * @param oldVsTag the value for deploy_vs.old_vs_tag
	 * @mbggenerated
	 */
	public void setOldVsTag(String oldVsTag) {
		this.oldVsTag = oldVsTag == null ? null : oldVsTag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_vs.summary_log
	 *
	 * @return the value of deploy_vs.summary_log
	 * @mbggenerated
	 */
	public String getSummaryLog() {
		return summaryLog;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_vs.summary_log
	 *
	 * @param summaryLog the value for deploy_vs.summary_log
	 * @mbggenerated
	 */
	public void setSummaryLog(String summaryLog) {
		this.summaryLog = summaryLog == null ? null : summaryLog.trim();
	}
}