package com.dianping.phoenix.lb.deploy.model.api;

import com.dianping.phoenix.lb.deploy.model.DeployTaskStatus;
import com.dianping.phoenix.lb.deploy.model.StateAction;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeployTaskApiExample {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	public DeployTaskApiExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(DeployTaskStatus value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(DeployTaskStatus value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(DeployTaskStatus value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(DeployTaskStatus value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(DeployTaskStatus value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(DeployTaskStatus value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(DeployTaskStatus value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(DeployTaskStatus value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<DeployTaskStatus> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<DeployTaskStatus> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(DeployTaskStatus value1, DeployTaskStatus value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(DeployTaskStatus value1, DeployTaskStatus value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andDeployedByIsNull() {
			addCriterion("deployed_by is null");
			return (Criteria) this;
		}

		public Criteria andDeployedByIsNotNull() {
			addCriterion("deployed_by is not null");
			return (Criteria) this;
		}

		public Criteria andDeployedByEqualTo(String value) {
			addCriterion("deployed_by =", value, "deployedBy");
			return (Criteria) this;
		}

		public Criteria andDeployedByNotEqualTo(String value) {
			addCriterion("deployed_by <>", value, "deployedBy");
			return (Criteria) this;
		}

		public Criteria andDeployedByGreaterThan(String value) {
			addCriterion("deployed_by >", value, "deployedBy");
			return (Criteria) this;
		}

		public Criteria andDeployedByGreaterThanOrEqualTo(String value) {
			addCriterion("deployed_by >=", value, "deployedBy");
			return (Criteria) this;
		}

		public Criteria andDeployedByLessThan(String value) {
			addCriterion("deployed_by <", value, "deployedBy");
			return (Criteria) this;
		}

		public Criteria andDeployedByLessThanOrEqualTo(String value) {
			addCriterion("deployed_by <=", value, "deployedBy");
			return (Criteria) this;
		}

		public Criteria andDeployedByLike(String value) {
			addCriterion("deployed_by like", value, "deployedBy");
			return (Criteria) this;
		}

		public Criteria andDeployedByNotLike(String value) {
			addCriterion("deployed_by not like", value, "deployedBy");
			return (Criteria) this;
		}

		public Criteria andDeployedByIn(List<String> values) {
			addCriterion("deployed_by in", values, "deployedBy");
			return (Criteria) this;
		}

		public Criteria andDeployedByNotIn(List<String> values) {
			addCriterion("deployed_by not in", values, "deployedBy");
			return (Criteria) this;
		}

		public Criteria andDeployedByBetween(String value1, String value2) {
			addCriterion("deployed_by between", value1, value2, "deployedBy");
			return (Criteria) this;
		}

		public Criteria andDeployedByNotBetween(String value1, String value2) {
			addCriterion("deployed_by not between", value1, value2, "deployedBy");
			return (Criteria) this;
		}

		public Criteria andBeginDateIsNull() {
			addCriterion("begin_date is null");
			return (Criteria) this;
		}

		public Criteria andBeginDateIsNotNull() {
			addCriterion("begin_date is not null");
			return (Criteria) this;
		}

		public Criteria andBeginDateEqualTo(Date value) {
			addCriterion("begin_date =", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateNotEqualTo(Date value) {
			addCriterion("begin_date <>", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateGreaterThan(Date value) {
			addCriterion("begin_date >", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateGreaterThanOrEqualTo(Date value) {
			addCriterion("begin_date >=", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateLessThan(Date value) {
			addCriterion("begin_date <", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateLessThanOrEqualTo(Date value) {
			addCriterion("begin_date <=", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateIn(List<Date> values) {
			addCriterion("begin_date in", values, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateNotIn(List<Date> values) {
			addCriterion("begin_date not in", values, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateBetween(Date value1, Date value2) {
			addCriterion("begin_date between", value1, value2, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateNotBetween(Date value1, Date value2) {
			addCriterion("begin_date not between", value1, value2, "beginDate");
			return (Criteria) this;
		}

		public Criteria andEndDateIsNull() {
			addCriterion("end_date is null");
			return (Criteria) this;
		}

		public Criteria andEndDateIsNotNull() {
			addCriterion("end_date is not null");
			return (Criteria) this;
		}

		public Criteria andEndDateEqualTo(Date value) {
			addCriterion("end_date =", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotEqualTo(Date value) {
			addCriterion("end_date <>", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateGreaterThan(Date value) {
			addCriterion("end_date >", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
			addCriterion("end_date >=", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateLessThan(Date value) {
			addCriterion("end_date <", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateLessThanOrEqualTo(Date value) {
			addCriterion("end_date <=", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateIn(List<Date> values) {
			addCriterion("end_date in", values, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotIn(List<Date> values) {
			addCriterion("end_date not in", values, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateBetween(Date value1, Date value2) {
			addCriterion("end_date between", value1, value2, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotBetween(Date value1, Date value2) {
			addCriterion("end_date not between", value1, value2, "endDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateIsNull() {
			addCriterion("creation_date is null");
			return (Criteria) this;
		}

		public Criteria andCreationDateIsNotNull() {
			addCriterion("creation_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreationDateEqualTo(Date value) {
			addCriterion("creation_date =", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateNotEqualTo(Date value) {
			addCriterion("creation_date <>", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateGreaterThan(Date value) {
			addCriterion("creation_date >", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateGreaterThanOrEqualTo(Date value) {
			addCriterion("creation_date >=", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateLessThan(Date value) {
			addCriterion("creation_date <", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateLessThanOrEqualTo(Date value) {
			addCriterion("creation_date <=", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateIn(List<Date> values) {
			addCriterion("creation_date in", values, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateNotIn(List<Date> values) {
			addCriterion("creation_date not in", values, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateBetween(Date value1, Date value2) {
			addCriterion("creation_date between", value1, value2, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateNotBetween(Date value1, Date value2) {
			addCriterion("creation_date not between", value1, value2, "creationDate");
			return (Criteria) this;
		}

		public Criteria andLastModifiedDateIsNull() {
			addCriterion("last_modified_date is null");
			return (Criteria) this;
		}

		public Criteria andLastModifiedDateIsNotNull() {
			addCriterion("last_modified_date is not null");
			return (Criteria) this;
		}

		public Criteria andLastModifiedDateEqualTo(Date value) {
			addCriterion("last_modified_date =", value, "lastModifiedDate");
			return (Criteria) this;
		}

		public Criteria andLastModifiedDateNotEqualTo(Date value) {
			addCriterion("last_modified_date <>", value, "lastModifiedDate");
			return (Criteria) this;
		}

		public Criteria andLastModifiedDateGreaterThan(Date value) {
			addCriterion("last_modified_date >", value, "lastModifiedDate");
			return (Criteria) this;
		}

		public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
			addCriterion("last_modified_date >=", value, "lastModifiedDate");
			return (Criteria) this;
		}

		public Criteria andLastModifiedDateLessThan(Date value) {
			addCriterion("last_modified_date <", value, "lastModifiedDate");
			return (Criteria) this;
		}

		public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
			addCriterion("last_modified_date <=", value, "lastModifiedDate");
			return (Criteria) this;
		}

		public Criteria andLastModifiedDateIn(List<Date> values) {
			addCriterion("last_modified_date in", values, "lastModifiedDate");
			return (Criteria) this;
		}

		public Criteria andLastModifiedDateNotIn(List<Date> values) {
			addCriterion("last_modified_date not in", values, "lastModifiedDate");
			return (Criteria) this;
		}

		public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
			addCriterion("last_modified_date between", value1, value2, "lastModifiedDate");
			return (Criteria) this;
		}

		public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
			addCriterion("last_modified_date not between", value1, value2, "lastModifiedDate");
			return (Criteria) this;
		}

		public Criteria andStateActionIsNull() {
			addCriterion("state_action is null");
			return (Criteria) this;
		}

		public Criteria andStateActionIsNotNull() {
			addCriterion("state_action is not null");
			return (Criteria) this;
		}

		public Criteria andStateActionEqualTo(StateAction value) {
			addCriterion("state_action =", value, "stateAction");
			return (Criteria) this;
		}

		public Criteria andStateActionNotEqualTo(StateAction value) {
			addCriterion("state_action <>", value, "stateAction");
			return (Criteria) this;
		}

		public Criteria andStateActionGreaterThan(StateAction value) {
			addCriterion("state_action >", value, "stateAction");
			return (Criteria) this;
		}

		public Criteria andStateActionGreaterThanOrEqualTo(StateAction value) {
			addCriterion("state_action >=", value, "stateAction");
			return (Criteria) this;
		}

		public Criteria andStateActionLessThan(StateAction value) {
			addCriterion("state_action <", value, "stateAction");
			return (Criteria) this;
		}

		public Criteria andStateActionLessThanOrEqualTo(StateAction value) {
			addCriterion("state_action <=", value, "stateAction");
			return (Criteria) this;
		}

		public Criteria andStateActionLike(StateAction value) {
			addCriterion("state_action like", value, "stateAction");
			return (Criteria) this;
		}

		public Criteria andStateActionNotLike(StateAction value) {
			addCriterion("state_action not like", value, "stateAction");
			return (Criteria) this;
		}

		public Criteria andStateActionIn(List<StateAction> values) {
			addCriterion("state_action in", values, "stateAction");
			return (Criteria) this;
		}

		public Criteria andStateActionNotIn(List<StateAction> values) {
			addCriterion("state_action not in", values, "stateAction");
			return (Criteria) this;
		}

		public Criteria andStateActionBetween(StateAction value1, StateAction value2) {
			addCriterion("state_action between", value1, value2, "stateAction");
			return (Criteria) this;
		}

		public Criteria andStateActionNotBetween(StateAction value1, StateAction value2) {
			addCriterion("state_action not between", value1, value2, "stateAction");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated do_not_delete_during_merge
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}
	}
}