package com.dianping.phoenix.lb.deploy.model.api;

import com.dianping.phoenix.lb.deploy.model.DeployAgentStatus;

import java.io.Serializable;
import java.util.Date;

public class DeployAgentApi implements Serializable {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table deploy_agent_api
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_agent_api.id
	 *
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_agent_api.deploy_task_id
	 *
	 * @mbggenerated
	 */
	private Long deployTaskId;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_agent_api.ip_address
	 *
	 * @mbggenerated
	 */
	private String ipAddress;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_agent_api.vs_names
	 *
	 * @mbggenerated
	 */
	private String vsNames;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_agent_api.vs_tags
	 *
	 * @mbggenerated
	 */
	private String vsTags;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_agent_api.status
	 *
	 * @mbggenerated
	 */
	private DeployAgentStatus status;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_agent_api.begin_date
	 *
	 * @mbggenerated
	 */
	private Date beginDate;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_agent_api.end_date
	 *
	 * @mbggenerated
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_agent_api.creation_date
	 *
	 * @mbggenerated
	 */
	private Date creationDate;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_agent_api.last_modified_date
	 *
	 * @mbggenerated
	 */
	private Date lastModifiedDate;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_agent_api.raw_log
	 *
	 * @mbggenerated
	 */
	private String rawLog;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_agent_api.id
	 *
	 * @return the value of deploy_agent_api.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_agent_api.id
	 *
	 * @param id the value for deploy_agent_api.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_agent_api.deploy_task_id
	 *
	 * @return the value of deploy_agent_api.deploy_task_id
	 * @mbggenerated
	 */
	public Long getDeployTaskId() {
		return deployTaskId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_agent_api.deploy_task_id
	 *
	 * @param deployTaskId the value for deploy_agent_api.deploy_task_id
	 * @mbggenerated
	 */
	public void setDeployTaskId(Long deployTaskId) {
		this.deployTaskId = deployTaskId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_agent_api.ip_address
	 *
	 * @return the value of deploy_agent_api.ip_address
	 * @mbggenerated
	 */
	public String getIpAddress() {
		return ipAddress;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_agent_api.ip_address
	 *
	 * @param ipAddress the value for deploy_agent_api.ip_address
	 * @mbggenerated
	 */
	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress == null ? null : ipAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_agent_api.vs_names
	 *
	 * @return the value of deploy_agent_api.vs_names
	 * @mbggenerated
	 */
	public String getVsNames() {
		return vsNames;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_agent_api.vs_names
	 *
	 * @param vsNames the value for deploy_agent_api.vs_names
	 * @mbggenerated
	 */
	public void setVsNames(String vsNames) {
		this.vsNames = vsNames == null ? null : vsNames.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_agent_api.vs_tags
	 *
	 * @return the value of deploy_agent_api.vs_tags
	 * @mbggenerated
	 */
	public String getVsTags() {
		return vsTags;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_agent_api.vs_tags
	 *
	 * @param vsTags the value for deploy_agent_api.vs_tags
	 * @mbggenerated
	 */
	public void setVsTags(String vsTags) {
		this.vsTags = vsTags == null ? null : vsTags.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_agent_api.status
	 *
	 * @return the value of deploy_agent_api.status
	 * @mbggenerated
	 */
	public DeployAgentStatus getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_agent_api.status
	 *
	 * @param status the value for deploy_agent_api.status
	 * @mbggenerated
	 */
	public void setStatus(DeployAgentStatus status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_agent_api.begin_date
	 *
	 * @return the value of deploy_agent_api.begin_date
	 * @mbggenerated
	 */
	public Date getBeginDate() {
		return beginDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_agent_api.begin_date
	 *
	 * @param beginDate the value for deploy_agent_api.begin_date
	 * @mbggenerated
	 */
	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_agent_api.end_date
	 *
	 * @return the value of deploy_agent_api.end_date
	 * @mbggenerated
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_agent_api.end_date
	 *
	 * @param endDate the value for deploy_agent_api.end_date
	 * @mbggenerated
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_agent_api.creation_date
	 *
	 * @return the value of deploy_agent_api.creation_date
	 * @mbggenerated
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_agent_api.creation_date
	 *
	 * @param creationDate the value for deploy_agent_api.creation_date
	 * @mbggenerated
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_agent_api.last_modified_date
	 *
	 * @return the value of deploy_agent_api.last_modified_date
	 * @mbggenerated
	 */
	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_agent_api.last_modified_date
	 *
	 * @param lastModifiedDate the value for deploy_agent_api.last_modified_date
	 * @mbggenerated
	 */
	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_agent_api.raw_log
	 *
	 * @return the value of deploy_agent_api.raw_log
	 * @mbggenerated
	 */
	public String getRawLog() {
		return rawLog;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_agent_api.raw_log
	 *
	 * @param rawLog the value for deploy_agent_api.raw_log
	 * @mbggenerated
	 */
	public void setRawLog(String rawLog) {
		this.rawLog = rawLog == null ? null : rawLog.trim();
	}
}