package com.dianping.phoenix.lb.deploy.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AgentIdSequenceExample {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	public AgentIdSequenceExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAgentIdIsNull() {
			addCriterion("agent_id is null");
			return (Criteria) this;
		}

		public Criteria andAgentIdIsNotNull() {
			addCriterion("agent_id is not null");
			return (Criteria) this;
		}

		public Criteria andAgentIdEqualTo(Long value) {
			addCriterion("agent_id =", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNotEqualTo(Long value) {
			addCriterion("agent_id <>", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdGreaterThan(Long value) {
			addCriterion("agent_id >", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdGreaterThanOrEqualTo(Long value) {
			addCriterion("agent_id >=", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdLessThan(Long value) {
			addCriterion("agent_id <", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdLessThanOrEqualTo(Long value) {
			addCriterion("agent_id <=", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdIn(List<Long> values) {
			addCriterion("agent_id in", values, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNotIn(List<Long> values) {
			addCriterion("agent_id not in", values, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdBetween(Long value1, Long value2) {
			addCriterion("agent_id between", value1, value2, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNotBetween(Long value1, Long value2) {
			addCriterion("agent_id not between", value1, value2, "agentId");
			return (Criteria) this;
		}

		public Criteria andCreationDateIsNull() {
			addCriterion("creation_date is null");
			return (Criteria) this;
		}

		public Criteria andCreationDateIsNotNull() {
			addCriterion("creation_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreationDateEqualTo(Date value) {
			addCriterion("creation_date =", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateNotEqualTo(Date value) {
			addCriterion("creation_date <>", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateGreaterThan(Date value) {
			addCriterion("creation_date >", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateGreaterThanOrEqualTo(Date value) {
			addCriterion("creation_date >=", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateLessThan(Date value) {
			addCriterion("creation_date <", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateLessThanOrEqualTo(Date value) {
			addCriterion("creation_date <=", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateIn(List<Date> values) {
			addCriterion("creation_date in", values, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateNotIn(List<Date> values) {
			addCriterion("creation_date not in", values, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateBetween(Date value1, Date value2) {
			addCriterion("creation_date between", value1, value2, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateNotBetween(Date value1, Date value2) {
			addCriterion("creation_date not between", value1, value2, "creationDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated do_not_delete_during_merge
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}
	}
}