package com.dianping.phoenix.lb.deploy.model;

import java.io.Serializable;
import java.util.Date;

public class AgentIdSequence implements Serializable {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table agent_id_sequence
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column agent_id_sequence.agent_id
	 *
	 * @mbggenerated
	 */
	private Long agentId;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column agent_id_sequence.creation_date
	 *
	 * @mbggenerated
	 */
	private Date creationDate;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column agent_id_sequence.agent_id
	 *
	 * @return the value of agent_id_sequence.agent_id
	 * @mbggenerated
	 */
	public Long getAgentId() {
		return agentId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column agent_id_sequence.agent_id
	 *
	 * @param agentId the value for agent_id_sequence.agent_id
	 * @mbggenerated
	 */
	public void setAgentId(Long agentId) {
		this.agentId = agentId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column agent_id_sequence.creation_date
	 *
	 * @return the value of agent_id_sequence.creation_date
	 * @mbggenerated
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column agent_id_sequence.creation_date
	 *
	 * @param creationDate the value for agent_id_sequence.creation_date
	 * @mbggenerated
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}
}