package com.dianping.phoenix.lb.deploy.dao;

import com.dianping.phoenix.lb.deploy.model.DeployTask;
import com.dianping.phoenix.lb.deploy.model.DeployTaskExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface DeployTaskMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task
	 *
	 * @mbggenerated
	 */
	int countByExample(DeployTaskExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task
	 *
	 * @mbggenerated
	 */
	int deleteByExample(DeployTaskExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task
	 *
	 * @mbggenerated
	 */
	int insert(DeployTask record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task
	 *
	 * @mbggenerated
	 */
	int insertSelective(DeployTask record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task
	 *
	 * @mbggenerated
	 */
	List<DeployTask> selectByExampleWithRowbounds(DeployTaskExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task
	 *
	 * @mbggenerated
	 */
	List<DeployTask> selectByExample(DeployTaskExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task
	 *
	 * @mbggenerated
	 */
	DeployTask selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(
			@Param("record")
			DeployTask record,
			@Param("example")
			DeployTaskExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task
	 *
	 * @mbggenerated
	 */
	int updateByExample(
			@Param("record")
			DeployTask record,
			@Param("example")
			DeployTaskExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DeployTask record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_task
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DeployTask record);
}