package com.dianping.phoenix.lb.deploy.dao;

import com.dianping.phoenix.lb.deploy.model.DeployVs;
import com.dianping.phoenix.lb.deploy.model.DeployVsExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface DeployVsMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	int countByExample(DeployVsExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	int deleteByExample(DeployVsExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	int insert(DeployVs record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	int insertSelective(DeployVs record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	List<DeployVs> selectByExampleWithBLOBsWithRowbounds(DeployVsExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	List<DeployVs> selectByExampleWithBLOBs(DeployVsExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	List<DeployVs> selectByExampleWithRowbounds(DeployVsExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	List<DeployVs> selectByExample(DeployVsExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	DeployVs selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(
			@Param("record")
			DeployVs record,
			@Param("example")
			DeployVsExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(
			@Param("record")
			DeployVs record,
			@Param("example")
			DeployVsExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	int updateByExample(
			@Param("record")
			DeployVs record,
			@Param("example")
			DeployVsExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DeployVs record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(DeployVs record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table deploy_vs
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DeployVs record);
}