package com.dianping.phoenix.lb.deploy.model.api;

import com.dianping.phoenix.lb.deploy.model.DeployTaskStatus;
import com.dianping.phoenix.lb.deploy.model.StateAction;

import java.io.Serializable;
import java.util.Date;

public class DeployTaskApi implements Serializable {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table deploy_task_api
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_task_api.id
	 *
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_task_api.name
	 *
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_task_api.status
	 *
	 * @mbggenerated
	 */
	private DeployTaskStatus status;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_task_api.deployed_by
	 *
	 * @mbggenerated
	 */
	private String deployedBy;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_task_api.begin_date
	 *
	 * @mbggenerated
	 */
	private Date beginDate;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_task_api.end_date
	 *
	 * @mbggenerated
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_task_api.creation_date
	 *
	 * @mbggenerated
	 */
	private Date creationDate;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_task_api.last_modified_date
	 *
	 * @mbggenerated
	 */
	private Date lastModifiedDate;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_task_api.state_action
	 *
	 * @mbggenerated
	 */
	private StateAction stateAction;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column deploy_task_api.summary_log
	 *
	 * @mbggenerated
	 */
	private String summaryLog;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_task_api.id
	 *
	 * @return the value of deploy_task_api.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_task_api.id
	 *
	 * @param id the value for deploy_task_api.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_task_api.name
	 *
	 * @return the value of deploy_task_api.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_task_api.name
	 *
	 * @param name the value for deploy_task_api.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_task_api.status
	 *
	 * @return the value of deploy_task_api.status
	 * @mbggenerated
	 */
	public DeployTaskStatus getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_task_api.status
	 *
	 * @param status the value for deploy_task_api.status
	 * @mbggenerated
	 */
	public void setStatus(DeployTaskStatus status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_task_api.deployed_by
	 *
	 * @return the value of deploy_task_api.deployed_by
	 * @mbggenerated
	 */
	public String getDeployedBy() {
		return deployedBy;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_task_api.deployed_by
	 *
	 * @param deployedBy the value for deploy_task_api.deployed_by
	 * @mbggenerated
	 */
	public void setDeployedBy(String deployedBy) {
		this.deployedBy = deployedBy == null ? null : deployedBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_task_api.begin_date
	 *
	 * @return the value of deploy_task_api.begin_date
	 * @mbggenerated
	 */
	public Date getBeginDate() {
		return beginDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_task_api.begin_date
	 *
	 * @param beginDate the value for deploy_task_api.begin_date
	 * @mbggenerated
	 */
	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_task_api.end_date
	 *
	 * @return the value of deploy_task_api.end_date
	 * @mbggenerated
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_task_api.end_date
	 *
	 * @param endDate the value for deploy_task_api.end_date
	 * @mbggenerated
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_task_api.creation_date
	 *
	 * @return the value of deploy_task_api.creation_date
	 * @mbggenerated
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_task_api.creation_date
	 *
	 * @param creationDate the value for deploy_task_api.creation_date
	 * @mbggenerated
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_task_api.last_modified_date
	 *
	 * @return the value of deploy_task_api.last_modified_date
	 * @mbggenerated
	 */
	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_task_api.last_modified_date
	 *
	 * @param lastModifiedDate the value for deploy_task_api.last_modified_date
	 * @mbggenerated
	 */
	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_task_api.state_action
	 *
	 * @return the value of deploy_task_api.state_action
	 * @mbggenerated
	 */
	public StateAction getStateAction() {
		return stateAction;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_task_api.state_action
	 *
	 * @param stateAction the value for deploy_task_api.state_action
	 * @mbggenerated
	 */
	public void setStateAction(StateAction stateAction) {
		this.stateAction = stateAction;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column deploy_task_api.summary_log
	 *
	 * @return the value of deploy_task_api.summary_log
	 * @mbggenerated
	 */
	public String getSummaryLog() {
		return summaryLog;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column deploy_task_api.summary_log
	 *
	 * @param summaryLog the value for deploy_task_api.summary_log
	 * @mbggenerated
	 */
	public void setSummaryLog(String summaryLog) {
		this.summaryLog = summaryLog == null ? null : summaryLog.trim();
	}
}